### ISSUE TITLE
Error on disconnect from server

### ISSUE THREAD

**Issue by mezz** [kihira/Tails#71]
When disconnecting from the ForgeCraft server, its seems to hang forever.
I saw this error in the log, I think it may be the cause.

```
[22:20:26] [Netty Client IO #1/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.network.FMLNetworkEvent$ClientDisconnectionFromServerEvent@602b30f8:
java.lang.NullPointerException
	at uk.kihira.tails.client.ClientEventHandler.onDisconnect(ClientEventHandler.java:71) ~[ClientEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_548_ClientEventHandler_onDisconnect_ClientDisconnectionFromServerEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.close(NetworkDispatcher.java:496) [NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:568) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$1200(AbstractChannelHandlerContext.java:32) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext$14.run(AbstractChannelHandlerContext.java:558) [AbstractChannelHandlerContext$14.class:4.0.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [SingleThreadEventExecutor.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [NioEventLoop.class:4.0.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
```

**Comment by mezz** [comment]
Thanks, that looks the same.
We have 1.8.2, I'll try the latest.

**Comment by mezz** [comment]
Confirmed fixed, thank you very much.

**Comment by kihira** [comment]
Yup, I completely forgot to add the new version >.<
